name: LLM Pipeline CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  

          

  kubeflow-pipeline-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install kfp
        run: pip install kfp==1.8.22
        
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > $HOME/.kube/config

      - name: Compile and Deploy Kubeflow Pipeline
        env:
          KFP_HOST: ${{ secrets.KFP_HOST }}
        run: |
          python3 pipeline.py
