name: LLM Pipeline CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: maamounm/llm_pipeline:latest

          build-args: |
              BUILDKIT_INLINE_CACHE=1
          cache-from: type=registry,ref=maamounm/llm_pipeline:latest
          cache-to: type=inline

  kubeflow-pipeline-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install kfp
        run: pip install kfp==1.8.22
        
      - name: Compile and Deploy Kubeflow Pipeline
        env:
          KFP_HOST: ${{ secrets.KFP_HOST }}
        run: |
          python3 pipeline.py
